### PR TITLE
Linux and Windows builds in a container, start a OSX build.

### PR DESCRIPTION
**Pull request by nsg**
This PR downloads a prepared Docker image, based on Ubuntu 15.10 and builds the Linux builds, and the cross compiled builds for Windows. I also starts a OSX dummy-build.

### CODE REVIEW

**Comment by nsg** [comment]
@petterarvidsson I *think* that the Linux builds works, you can try to merge these changes to our branch if you like and test it.

**Comment by nsg** [comment]
Did a `cmake .` and `make` on OSX, no packages installed ... it built, with clang.

**Comment by nsg** [comment]
@petterarvidsson ready to be merged

**Comment by petterarvidsson** [comment]
@nsg :+1:

**Pull request merged**
