### PR TITLE
Add support for CAF

### PR DESCRIPTION
**Pull request by petterarvidsson**

### CODE REVIEW

**Comment by petterarvidsson** [comment]
It seems travis [uses an ancient g++](https://github.com/travis-ci/travis-ci/issues/1379)

**Comment by nsg** [comment]
Yeah, I think it's time to try to move away from the legacy infrastructure, it is based on Ubuntu 12.04 if I remember correctly. [I tried out the new Docker based solution last weekend](https://travis-ci.org/nsg/ansible-graphite) where I test an Ansible role in five different containers, each running my image with my packages. Works perfectly!

**Comment by petterarvidsson** [comment]
@nsg Docker would be very nice. It's enough to run 14.04 to get GCC 4.8+ for both the standard compiler and mingw, I could not find any mingw 4.9 compiler for 12.04, so I was kind f stuck yesterday in getting the windows build working.

**Comment by petterarvidsson** [comment]
Finally got a decent build where it now only builds the targets I want and not like 10 different programs that we are not using.

**Comment by nsg** [comment]
Sounds good!

**Comment by nsg** [comment]
@petterarvidsson close this I guess?

**Pull request closed without merging**
