### PR TITLE
Rework chunk loading

### PR DESCRIPTION
**Pull request by petterarvidsson**

### CODE REVIEW

**Comment by nsg** [comment]
I did a test with 4d6be0d and I have been running the client for over a hour now loading plenty of chunks with no traces of the problems of yesterday. A few thoughts:

* I have never seen my view distance go under 19 (19+2=21) so I'm not even sure if this change matters?
* I'm a little worried that the lock can cause performance problems? I'm just being silly now, or?

Over all, what do you think about this change @petterarvidsson

**Comment by nsg** [comment]
@petterarvidsson I have updated with the commit 0bc1956 that uses the local variable, and 8f5c5c9 that replaces most instances of `max_radius` with `radius`.

**Comment by nsg** [comment]
I will close this branch with experiments now and open a new PR's with some changes discovered here :)

**Comment by petterarvidsson** [comment]
@nsg A new attempt based on your changes. On my computer it seems to behave a lot better than before consuming much less CPU

**Comment by nsg** [comment]
screenshot from 2016-06-29 19 16 09

**Comment by petterarvidsson** [comment]
@nsg For me this seems to work quite well now. I have made some cleanups and removed the chunk ordering (it only makes chunks close to each other to be more in order, doesn't really add much and it added extra complexity to the code). What do you think, should we go with this one and close #194 and #195 which are both included here?

**Pull request merged**
