### PR TITLE
Look for textures in ../textures as well.

### LINKED ISSUE #119: Can't find the textures form a sub directory
Textures are included from `textures/foo.png`, this will not work if we have built the binary inside a subdirectory and starts it with ./konstructs. Update the code to fall back to `../textures/foo.png`before giving up.

### PR DESCRIPTION
**Pull request by nsg**
This fixes #119

### CODE REVIEW

**Comment by nsg** [comment]
@petterarvidsson ready for review!

**Comment by Henningstone** [comment]
You know what? I did *exacty* the same. And I did it *exactly* the same time you did it. (Look https://github.com/Henningstone/client/commit/51a9f16680bb3099978b37dd614a8a45912c9135)
I can tell you, it's tested and it works :P

**Comment by nsg** [comment]
@Henningstone wow, we are synchronized :)

**Comment by petterarvidsson** [comment]
@nsg & @Henningstone Looking good!

**Pull request merged**
