### PR TITLE
Add and use nanogui to the project

### PR DESCRIPTION
**Pull request by petterarvidsson**
* Remove CPM and replace with git submodules and add_subdirectory(...)
* Add NanoGUI to manage OpenGL, and use it to draw UI elements (NanoGUI also adds Eigen to the toolbox).
* Use and extend the shader tools from NanoGUI to load and update shader data.
* Rewrite render, package and various C functions to C++ classes.
* Various fixes to the build system for the new stack.
* Generate documentation with Doxygen.

### CODE REVIEW

**Comment by nsg** [comment]
@petterarvidsson I was playing around with Doxygen earlier to generate docs, works nicely. The problem is that there are no way to setup a secure way to update the GH pages so I need to think about this ... maybe the easiest approach is just to host the files on a external server ...

**Comment by petterarvidsson** [comment]
@nsg I have been moving more and more parts and now have a client that nearly can receive chunks and render them. Will continue tomorrow. :+1: for doxygen :-)

**Comment by nsg** [comment]
@petterarvidsson oh, that's awesome!

**Comment by petterarvidsson** [comment]
screenshot from 2015-11-09 10 23 22

Time to add back support for textures. It looks like it is actually rendering the real thing.

**Comment by nsg** [comment]
@petterarvidsson Really nice, looking forward to see the textures again :) If I'm not to tired I will upload the doxygen docs somewhere this evening. I will also try to give the cross compile problem some attention.

**Comment by petterarvidsson** [comment]
screenshot from 2015-11-09 18 28 12

All the flowers!

**Comment by nsg** [comment]
@petterarvidsson :+1 :)

**Comment by nsg** [comment]
Imgur

Nice!

**Comment by petterarvidsson** [comment]
screenshot from 2015-12-05 21 56 46

View distance 20 (that is 640 blocks!) running on my laptop's Intel graphic card. very playable (rendering all those chunks takes some time though :-) ). All the hard porting work is finally paying off!

**Comment by petterarvidsson** [comment]
screenshot from 2015-12-05 22 42 59

Did a test with view distance 40. It was still computing chunks when I took this one. view distance 40 means ~100000 chunks needs to be calculated and the horizon is 1280 blocks away! It was not really playable any more on my card (one could notice when turning around that the drivers had to upload the models since all didn't fit in graphics ram). The actual number of vertices rendered was still within what my card can handle, so only looking in one direction the game is "playable"

The vantage point is the same as before, but a bit higher up so that the much longer view distance is noticeable. I also waited for one of @Henningstone's nice sun sets to provided the right setting :-)

**Comment by nsg** [comment]
screenshot from 2015-12-13 15 16 21

Yey! In the red!

**Comment by petterarvidsson** [comment]
screenshot from 2015-12-14 18 09 24

Initial HUD graphics.

**Comment by nsg** [comment]
Looking good!

**Comment by petterarvidsson** [comment]
Hud with simple ItemStack rendering.
screenshot from 2015-12-20 23 47 21

**Comment by nsg** [comment]
I updated the Doxygen documentation generation a little.
* Added a few custom html/css files to give it a more "konstructs feel", will improve this later.
* Hide private and other non-public data.

**Comment by petterarvidsson** [comment]
@nsg Nice!

**Comment by nsg** [comment]
Added a better working demo menu, `F1` is now a menu toggle.
Something is incorrectly overwritten (texture?) or maybe we need to set or unset some OpenGL mode ... hm.

**Comment by dragonly** [comment]
very interested! I'm a graduate student, and looked through your website yesterday. I've implemented a toy demo in Haskell (https://github.com/dragonly/HasCraft) inspired by fogleman's python demo. And When I was looking at the fork graph, I found your guys! Is there any suggestions on how I can start peeking into this awesome project? thx :)

**Comment by nsg** [comment]
Welcome @dragonly 

Nice to see some Haskell again, I haven't touched it since the second (or was it third?) year at university. I have never considered using it for OpenGL, I used it mostly to write algorithms of different kinds :) Then of course, I'm the sysadmin, @petterarvidsson is the real programmer :)

What interests you? konstructs/client is a C++11 OpenGL project and [konstructs/server](https://github.com/konstructs/server) is a Scala project with actors (Akka). We are also working on the plugin system for the server, you will be able to use both Java and Scala for that, we are also considering a REST API for the future.

Anything specific that pique your interests?

**Comment by dragonly** [comment]
@nsg Actually that Haskell project is for a course of Haskell, and I was just knocking into that MineCraft demo and then some crazy stuffs just broke into my head of using this new language to make an OpenGL demo :), which is just of a lot fun!
It's hard to say which part interests me, or put it another way: the whole thing! Because I haven't implemented any multi-user/3D/whatever game on my own. And I'm quite a novice to Java/Scala, but that shouldn't be a problem XD. And I also lack some sort of in depth understanding of OpenGL. So I think it's really a good starting point for soooo much goals.
Maybe I should first start reading some of your code and then try to find out something I could be helpful?
PS: The thing I was first astonished by this project is the sunset screenshot on the project home page. That's really beautiful!

**Comment by nsg** [comment]
@dragonly ah, I see :)

Sure, check out the code and look around. If you have any questions I recommend Gitter (linked from the README), it's a chat system integrated nicely with GitHub, or just ask here if you prefer :)

If you like to try this branch you need the branch `feature-release-3-updates` from [konstructs/server](https://github.com/konstructs/server). We hope to merge everything to master (both server and client) in a few days.

Me and @petterarvidsson will have a on-site coding session tomorrow, the plan is to publish a much needed roadmap for the future and write down all our plans and ideas. No point to keep them to our self :)

**Comment by nsg** [comment]
merge it @petterarvidsson :+1:

**Comment by petterarvidsson** [comment]
Let's do it, even though we added 3 lines more than removed :-/ "+6,066 −6,063"

**Pull request merged**
