### PR TITLE
Changes for windows compile

### PR DESCRIPTION
**Pull request by caseymcc**
Modified cmake.
altered WinSock include.
Changed calloc to std::vector

### CODE REVIEW

**Comment by petterarvidsson** [comment]
@nsg I think this looks great, I'd like to squash and merge this one. What do you think?

**Comment by nsg** [comment]
@petterarvidsson yes, looks good! +1 for a squash and merge.

**Comment by petterarvidsson** [comment]
@caseymcc I wanted to remove the two last commits, therefore I squashed your branch locally to only keep your commit. This was merged here: https://github.com/konstructs/client/commit/7d538a2b39023c6afa7248aa81ec5593c7abc983

I will therefore close this PR now. In the future, please take the time to tidy up the commits in your PR using rebase so that it can be merged directly. This will also leave it as merged rather than closed as in this case.

Thank you for your contributions!

**Comment by petterarvidsson** [comment]
For refernce: https://github.com/konstructs/client/pull/201/commits/a9520fbe6d01da1a74059796598846627c5047bc is now part of master.

**Pull request closed without merging**
