### PR TITLE
Feature new chunk renderer

### PR DESCRIPTION
**Pull request by petterarvidsson**

### CODE REVIEW

**Comment by petterarvidsson** [comment]
@nsg I have rewritten the chunk shader so that it works with a compact integer format. Rather than sending 40 bytes of floats per vertex we are now sending 8 bytes of ints with plenty of expansion room! I got stuck extending it to render the damage and it was super annoying having to add yet another float for each small thing I wanted to send, so I thought I better do this change first. I also tried to clean up the shader a bit and provide documentation of what I have done. On my computer I can not really notice any big difference. Huge forests are still a bit laggy. In theory, we have no traded GPU power for a 5 times memory reduction. It would be interesting to hear what kind of view distance you can get on your gaming computer with this shader!

**Comment by petterarvidsson** [comment]
@nsg ready for testing!

Just change the max_radius on line 73 in main.cpp to whatever value you want for the max radius you want. Server will happily respond with any chunk, but will only keep you up to date to distance 10.

**Comment by petterarvidsson** [comment]
@nsg Did a couple of more updates. There are still some stuff to be fixed (like that you can never receive a chunk more than once even if the client has deleted it :-) ), but I would like to verify that you are also experiencing an improvement. Main thread load when staring at the sky (0 faces) is for me 30% CPU. when looking at stuff that is stable, but if FPS goes down it decreases (it waits more for the GPU). So I think I have now reached a point where the main thread is no longer likely to give FPS interruptions.

**Comment by nsg** [comment]
@petterarvidsson stable 60 fps all the way to to 10 now!

**Comment by petterarvidsson** [comment]
@nsg This is working stable for me now. I stumbled on a couple of more performance improvements on the way. Can you give it a spin as well to make sure it also works well on more powerful computers? I think we should merge then and I'll attack block damage rendering in a new branch.

**Comment by nsg** [comment]
screenshot from 2016-06-20 23 28 31

Tried with both server#master and server#feature-use-block-damage-when-destroying-blocks

Same problem, like this.

**Comment by petterarvidsson** [comment]
Weird. I can not reproduce it. Can you give me some hints on something you are doing to get that behaviour? (It is the behaviour that my last commit is supposed to fix.)

**Comment by nsg** [comment]
@petterarvidsson I think we can qualify it as a [pbcak](http://www.urbandictionary.com/define.php?term=pbcak) problem. It works perfectly :)

**Comment by petterarvidsson** [comment]
@nsg Cool, then I will squash a bit of all those commits and then merge this one.

**Pull request merged**
