### PR TITLE
Test remove graphics features

### PR DESCRIPTION
**Pull request by petterarvidsson**

### CODE REVIEW

**Comment by petterarvidsson** [comment]
@nsg This updates the client to work with three dimensional chunks sent by the server. Also fixes some lagging issues related to computing chunks on the main thread.

**Comment by nsg** [comment]
@petterarvidsson this do wonders with the lag spikes, 60fps and no lag what so ever when I tested against the reference world. Noticed no difference with the world render, that is a good thing consider this huge refactor. Looks good, just one thought, maybe add a reminder/issue to remind us to fix the hardcoded height value.

**Comment by petterarvidsson** [comment]
@nsg I think we should add an issue for that in the server. The client needs to interpolate the collision detection to have a smooth experience, but the heigh at which a badly placed player should be moved to should be the servers job. The server also needs to make sure that a player is not anywhere they shouldn't be. konstructs/server#63

**Comment by nsg** [comment]
@petterarvidsson agree

**Pull request merged**
