### PR TITLE
Add rotation and light to HUD item stacks

### LINKED ISSUE #110: Show items in 3d
Items in the inventory are not rotated atm, give them a nice rotation for a nicer 3d-look.
Give the selected item a little extra rotation.

### PR DESCRIPTION
**Pull request by petterarvidsson**
This fixes #110

### CODE REVIEW

**Comment by nsg** [comment]
screenshot from 2015-12-28 18 14 39

Maybe change the rotation on the picked up block a little, do not like the super-symmetrical look :)
If you like, we can take that in a separate PR :+1:

**Comment by petterarvidsson** [comment]
@nsg Rotation of the picked up block is on line 127, "M_PI / 4". Please find a value that you like!

**Comment by nsg** [comment]
screenshot from 2015-12-28 19 52 02

I like it better, what do you think @petterarvidsson ?

**Comment by petterarvidsson** [comment]
@nsg Much better! I'll rebase and then let's merge this one!

**Comment by nsg** [comment]
:+1:

**Comment by petterarvidsson** [comment]
@nsg We forgot to fix the plants :-)

**Comment by nsg** [comment]
@petterarvidsson oh :)

**Comment by petterarvidsson** [comment]
@nsg Added a quick fix for plants. What do you think?

**Comment by nsg** [comment]
@petterarvidsson 

* Pick up a plant
* Open tool sack
* Move it

I see artefacts in the corner of the screen, I guess you have miscalculated vertexes somewhere.

**Comment by petterarvidsson** [comment]
@nsg Try it now?

**Comment by nsg** [comment]
@petterarvidsson :+1:

**Comment by petterarvidsson** [comment]
Merge time!

**Pull request merged**
