### PR TITLE
Feature render block health bar

### PR DESCRIPTION
**Pull request by petterarvidsson**

### CODE REVIEW

**Comment by petterarvidsson** [comment]
@nsg Added basic health bar rendering looking like this:
screenshot from 2016-06-21 19 12 36

This is based on #188

**Comment by petterarvidsson** [comment]
Or as in [this video](https://www.youtube.com/watch?v=9wbxE8QbmQ8)

**Comment by nsg** [comment]
@petterarvidsson nice!

Just a thought, I feel like that I naturally expects the "almost broken block" to be no more than maybe 50% or so. Feels like we need a little stronger effect. What do you think?

**Comment by nsg** [comment]
Quick and dirty edit:

damage

... and with a `damage_weight` set to `0.6`. I like it better.

**Comment by petterarvidsson** [comment]
@nsg Like it! Please commit.

I was also thinking that we do ahve the option of having a much higher resolution for the damage texture. That could look cool as well, with gradients so that the cracks also deepens.

**Comment by nsg** [comment]
@petterarvidsson commited

Sounds interesting!

**Comment by petterarvidsson** [comment]
@nsg thinking more like this

**Comment by nsg** [comment]
I see, do you not think it would conflict a little with the block-y art style?

**Comment by petterarvidsson** [comment]
@nsg Like your new texture and setting!

**Comment by petterarvidsson** [comment]
Not sure, since it is an effect on the block-y art it could look cool :smile:

**Comment by petterarvidsson** [comment]
basically I am only thinking lines growing from the center, but also becoming deeper the more damage the block gets (not only longer)

**Comment by petterarvidsson** [comment]
@nsg Anyway, let's try that in another branch, I'd say this one is ready for merging?

**Comment by nsg** [comment]
@petterarvidsson sure

**Pull request merged**
